#!/bin/bash  

# Get configuration
if [ -f /etc/default/teeworlds-server-daemon ]; then
	. /etc/default/teeworlds-server-daemon
else
	echo '/etc/default/teeworlds-server-daemon not found'
	exit 1
fi

# Get lsb functions
if [ -f /lib/lsb/init-functions ]; then
	. /lib/lsb/init-functions
else
	echo '/lib/lsb/init-functions not found'
	exit 1
fi

# Get the date 
date=$(date +%Y/%m/%d)
hour=$(date +%H:%M)

# Commands
case "$1" in

	# Start servers
	start)
		log_begin_msg 'Starting Teeworlds servers...'

		# Count started server
		started=0
		total=0

		# Loop on config files
		for config in $(ls $SETTINGS | grep .cfg)
		do
			# Count all configs
			total=$(expr $total + 1)	

			# Check if already started 
			already=$(cat $RUNNING | grep "$config started" | wc -l)
			if [ $already = '1' ]
			then
				log_failure_msg "$config is already running"
				continue
			fi

			# Get absolute path
			log="$LOGS/$config.log"
			settings="$SETTINGS/$config"

			# Copy settings
			cp --remove-destination $settings $TMP
			tmpsettings="$TMP/$config"

			# Remove unwanted settings
			cat $tmpsettings | grep -v '#!' > $TMPFILE
			cat $TMPFILE | grep -v 'logfile' > $tmpsettings
			rm $TMPFILE

			# Get the server binary
			srv='vanilla'
			specialsrv=$(cat $settings | grep '#!' | wc -l)
			if [ $specialsrv = '1' ]
			then
				srv=$(cat $settings | grep '#!' | cut -d '!' -f 2)
			fi
			server="$SERVERS/$srv"

			# Erase previous running information
			sed -i "/$config/d" $RUNNING

			# Check if server binary exists
			if [ -f $server ]
			then
				# Start the server
				nohup $server -f $config > $log 2>&1 < /dev/null &

				# Get the PID and log it
				pid=$!
				echo "$config started $date $hour $pid" >> $RUNNING

				# Count started server
				started=$(expr $started + 1)

				# Server started
				log_success_msg "$config ($srv) started"
			else
				# No binary found 
				echo "$config stopped $date $hour binary '$srv' not found" >> $RUNNING
				log_failure_msg "$config: binary '$srv' not found"
			fi
		done

		# Success
		log_success_msg "$started/$total server(s) started"
		log_end_msg $?
	;;

	# Stop servers
	stop)
		log_begin_msg 'Stopping Teeworlds servers...'

		# Count stopped servers
		count=0

		# Loop on infos
		while read info
		do
			# If server is started
			started=$(echo $info | cut -d ' ' -f 2)
			if [ $started = 'started' ]
			then
				# Kill the server
				pid=$(echo $info | cut -d ' ' -f 5)
				kill $pid 

				# Replace info
				config=$(echo $info | cut -d ' ' -f 1)
				sed -i "/$config/d" $RUNNING
				echo "$config stopped $date $hour" >> $RUNNING

				# Count
				count=$(expr $count + 1)
			fi
		done < $RUNNING

		# Success
		log_success_msg "$count server(s) stopped"
		log_end_msg $?
	;;

	# Restart servers
	restart)
		# Stop and start servers
		$LAUNCHER stop
		$LAUNCHER start
	;;

	# Servers status
	status)
	;;

	# Servers infos
	info)
	;;

	# Servers loads
	loads)
	;;

	# Help
	*)
		log_success_msg "Usage: $LAUNCHER {start|stop|restart|status|info|loads}" 
	;;

# End of file
esac

